export const SEARCH_USERS = "SEARCH_USERS";

export const UPDATE_SEARCH_PERSON = "UPDATE_SEARCH_PERSON";

export const FILTER_SEARCH_PERSON = "FILTER_SEARCH_PERSON";

export const RESET_DATA = "RESET_DATA";
